# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Windows x64

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore Captcha.Net dependencies
      run: dotnet restore ./src/Captcha.Net/Captcha.Net.csproj

    - name: Build Captcha.Net
      run: dotnet build ./src/Captcha.Net/Captcha.Net.csproj --no-restore

    - name: Restore Captcha.Net.Test Dependencies
      run: dotnet restore ./src/Captcha.Net.Test/Captcha.Net.Test.csproj

    - name: Build Captcha.Net.Test Project
      run: dotnet build ./src/Captcha.Net.Test/Captcha.Net.Test.csproj --no-restore

    - name: Run Tests
      run: dotnet test ./src/Captcha.Net.Test/Captcha.Net.Test.csproj --no-build --verbosity normal
